### ISSUE TITLE
camel-elasticsearch-rest-kafka-connector indexId

### ISSUE THREAD

**Issue by seravat** [apache/camel-kafka-connector#1192]
Hello,

According to the camel docs for the camel-elasticsearch-rest component: https://camel.apache.org/components/3.4.x/elasticsearch-rest-component.html

When using the Index operation, we can set the document id by using the header "indexId".

Is this header being ignored in the camel-elasticsearch-rest-kafka-connector ?

**Comment by oscerd** [comment]
No, you can use the header.

You just need to use the prefix "CamelHeader.", so it will be something like "CamelHeader.indexId" in case you're using the sink connector.

So you'll need to add an header to your Kafka message with that name.

**Comment by seravat** [comment]
Thanks for the response Andrea,

I am setting this header before sending to kafka:

```
exchange.getIn().setHeader("indexId", exchangeId);
```

So you are saying it should be: ?

```
exchange.getIn().setHeader("CamelHeader.indexId", exchangeId);
```

Is that right?

**Comment by oscerd** [comment]
Are you using the kafka-connect connector related to the component or something else? Because you should not use plain Camel code in case of Kafka connector usage, so I suspect your question is related to plain Camel.

**Comment by seravat** [comment]
So we have some apps sending data to a few kafka topics and then we have a Kafka Connect cluster with camel-kafka-elastic sink connectors feeding data to elastic.

**Comment by oscerd** [comment]
If you have the are consuming from a kafka topic through the ES kafka connector sink, you'll need to have a kafka header in your Kafka record, named CamelHeader.indexId, this will be transformed before arriving the ES component to indexId only.

**Comment by seravat** [comment]
Tried that already, I must be doing something weird.

So, when I was sending a "indexId" header to the kafka topic, we had this message:

```
  Value (123 bytes): {"id":"223C079749B9779-0000000000000001","ftpFolder":"/mnt/m2/inflight/systemtest","numberOfRecords":597,"status":"ACTIVE"}
  Timestamp: 1622795526830
  Partition: 3
  Offset: 125
  Headers: ClientFileName=TRAX_SFTR_TRAN_SFTR002_20210511_6074.csv-9fd29f92-8518-4658-985a-4dd734a5be11,ClientFolderId=systemtest,ftp_folder=/mnt/m2/inflight/systemtest,**indexId=223C079749B9779-0000000000000001**,payload_id=223C079749B9779-0000000000000001,transactionId=MONNETTEDCOLU3166TEST10QA1REG6074
% Reached end of topic sftr-payload [3] at offset 126
```

If I try to send the "CamelHeader.indexId" header, then nothing related with this exists.

```
Key (27 bytes): /mnt/m2/inflight/systemtest
  Value (123 bytes): {"id":"223C079749B9779-0000000000000004","ftpFolder":"/mnt/m2/inflight/systemtest","numberOfRecords":597,"status":"ACTIVE"}
  Timestamp: 1622796256243
  Partition: 3
  Offset: 131
  Headers: ClientFileName=TRAX_SFTR_TRAN_SFTR002_20210511_6074.csv-596707e7-e68f-44bd-8c8f-e14945aab5c7,ClientFolderId=systemtest,ftp_folder=/mnt/m2/inflight/systemtest,payload_id=223C079749B9779-0000000000000004,transactionId=MONNETTEDCOLU3166TEST10QA1REG6074
```

I know it is a camel "issue", any ideas? 🤷🏼

**Comment by oscerd** [comment]
What is the camel kafka connector version?

**Comment by seravat** [comment]
camel-elasticsearch-rest-kafka-connector:0.7.1.fuse-800004-redhat-00001

**Comment by oscerd** [comment]
For Red Hat product you need to ask to Red Hat support.

**Comment by oscerd** [comment]
By the way I'll have a look with the same 0.7.1 from upstream. Can you please show the kafka connector configuration too?

**Comment by seravat** [comment]
Sure! By the way, we are using the Strimzi/AMQ streams operator 

```
spec:
  class: >-
    org.apache.camel.kafkaconnector.elasticsearchrest.CamelElasticsearchrestSinkConnector
  config:
    key.ignore: false
    topics: sftr-payload
    camel.sink.endpoint.hostAddresses: 'sftr-es-es-http:9200'
    transforms: 'createKey,extractString'
    camel.sink.endpoint.indexName: sftr-payload
    camel.component.elasticsearch-rest.enableSSL: false
    errors.tolerance: all
    camel.component.elasticsearch-rest.user: elastic
    errors.log.enable: true
    key.converter: org.apache.kafka.connect.storage.StringConverter
    camel.sink.endpoint.operation: Index
    camel.sink.endpoint.enableSSL: false
    errors.deadletterqueue.topic.name: dlq-sftr-payload
    errors.deadletterqueue.context.headers.enable: true
    errors.deadletterqueue.topic.replication.factor: 1
    camel.component.elasticsearch-rest.password: 1z9Z36u0K1emWIKBR514oj3T
    camel.sink.path.clusterName: sftr-es
  tasksMax: 2
```
