### ISSUE TITLE
Issue with camel-google-pubsub-kafka-connector sink configuration

### ISSUE THREAD

**Issue by simplifadmin** [apache/camel-kafka-connector#1209]
Issue when using [camel-google-pubsub-kafka-connector](https://camel.apache.org/camel-kafka-connector/0.7.x/connectors/camel-google-pubsub-kafka-sink-connector.html) as sink for Strimzi kafka.

I've created a KafkaConnect single-node cluster using camel kafka connect for Pubsub.

That works fine.

Please find the k8s files and the error msg.

Any idea of resolving the google-pubsub-kafka-connector for k8s?

K8s file for KafkaConnect

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect
  namespace: kafka
  annotations:
    # enable connect operator
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  #version: 2.6.0
  image: camel/my-connect:v1
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  jvmOptions:
    gcLoggingEnabled: false
  config:
    group.id: my-connect
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    offset.storage.topic: my-connect-offsets
    config.storage.topic: my-connect-configs
    status.storage.topic: my-connect-status
    config.storage.replication.factor: 3 #n for production per n brokers
    offset.storage.replication.factor: 3 #per broker
    status.storage.replication.factor: 3 #per broker
```

Issue with pubsub-kafka 
```
kind: KafkaConnector
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: pubsub-kafka
  namespace: kafka
  labels:
    # must match connect cluster name
    strimzi.io/cluster: my-connect
spec:
  tasksMax: 1
  class: org.apache.camel.kafkaconnector.googlepubsub.CamelGooglepubsubSinkConnector
  config:
    #The Google Cloud PubSub Project Id
    camel.sink.path.projectId: <Project Id>
    #The Destination Name. For the consumer this will be the subscription name, while for the producer this will be the topic name.
    camel.sink.path.destinationName: test-topic

```

error msg from KafkaConnect container
2021-06-14 13:18:35,037 ERROR Uncaught exception in REST call to /connectors/pubsub-kafka/config (org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper) [qtp977975287-18]
org.apache.kafka.common.config.ConfigException: Must configure one of topics or topics.regex
at org.apache.kafka.connect.runtime.SinkConnectorConfig.validate(SinkConnectorConfig.java:102)
at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:352)
at org.apache.kafka.connect.runtime.AbstractHerder.lambda$validateConnectorConfig$1(AbstractHerder.java:326)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)

``

**Comment by oscerd** [comment]
You didn't specify the projectid for google cloud pubsub service, also you didn't specify the credentials for accessing the cloud service. Please read the documentation and have a look at this example.

**Comment by oscerd** [comment]
https://github.com/apache/camel-examples/tree/main/examples/main-endpointdsl-google-pubsub/src/main/java/org/apache/camel/example

**Comment by simplifadmin** [comment]
The removed the projectID due to expose.

**Comment by simplifadmin** [comment]
Update kafka-pubsub
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: pubsub-kafka
  namespace: kafka
  labels:
  # must match connect cluster name
    strimzi.io/cluster: my-connect
spec:
  class: org.apache.camel.kafkaconnector.googlepubsub.CamelGooglepubsubSinkConnector
  tasksMax: 5
  config:
  #The Google Cloud PubSub Project Id
    camel.sink.path.projectId: test
    topics: test-topic
  #The Destination Name. For the consumer this will be the subscription name, while for the producer this will be the topic name.
    camel.sink.path.destinationName: test-topic

**Kafka-connect : output**

2021-06-14 13:47:59,095 INFO [Consumer clientId=connector-consumer-pubsub-kafka-0, groupId=connect-pubsub-kafka] Member connector-consumer-pubsub-kafka-0-921dcb28-9357-4ac4-a767-42898b659fdf sending LeaveGroup request to coordinator my-cluster-kafka-1.my-cluster-kafka-brokers.kafka.svc:9092 (id: 2147483646 rack: null) due to the consumer is being closed (org.apache.kafka.clients.consumer.internals.AbstractCoordinator) [task-thread-pubsub-kafka-0]

**Comment by oscerd** [comment]
You need to provide credentials. Also please report the version of the connector you're using.

**Comment by simplifadmin** [comment]
version: latest (0.7.X)

**Comment by oscerd** [comment]
The version is latest or 0.7.x.

What is the version of the jar you're installing and how are you installing the jar

**Comment by simplifadmin** [comment]
output from kafkaconnect:
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Request had insufficient authentication scopes.
at io.grpc.Status.asRuntimeException(Status.java:533)

**Comment by simplifadmin** [comment]
> The version is latest or 0.7.x.
> 
> What is the version of the jar you're installing and how are you installing the jar

I'm created GKE using 1.20 version ,not sure on the jar

**Comment by oscerd** [comment]
The version of the connector.

**Comment by simplifadmin** [comment]
Please how do I check it?

**Comment by simplifadmin** [comment]
The new look for authentication - Please this the way to implement serviceAccountKey?
```

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: pubsub-kafka
  namespace: kafka
  labels:
  # must match connect cluster name
    strimzi.io/cluster: my-connect
spec:
  class: org.apache.camel.kafkaconnector.googlepubsub.CamelGooglepubsubSinkConnector
  tasksMax: 5
  config:
  #The Google Cloud PubSub Project Id
    camel.sink.path.projectId: <projectID>
    topics: test-topic
  #The Destination Name. For the consumer this will be the subscription name, while for the producer this will be the topic name.
    camel.sink.path.destinationName: projects/project/topics/test-topic
  #The Service account key that can be used as credentials for the PubSub publisher/subscriber. 
    camel.component.google-pubsub.serviceAccountKey: "{{key.json}}"
integration:
    configuration:
    - type: "secret"
      value: "pubsub-key"
```

**Comment by oscerd** [comment]
No, you need to provide a file a pass the path to the service account key file. You can get the file from the google pubsub console.

**Comment by simplifadmin** [comment]
Here's an update

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: pubsub-kafka
  namespace: kafka
  labels:
  # must match connect cluster name
    strimzi.io/cluster: my-connect
spec:
  class: org.apache.camel.kafkaconnector.googlepubsub.CamelGooglepubsubSinkConnector
  tasksMax: 5
  config:
  #The Google Cloud PubSub Project Id
    camel.sink.path.projectId: projected
    topics: test-topic
  #The Destination Name. For the consumer this will be the subscription name, while for the producer this will be the topic name.
    camel.sink.path.destinationName: projects/senseviewapi/topics/test-topic
  #The Service account key that can be used as credentials for the PubSub publisher/subscriber. 
    camel.component.google-pubsub.serviceAccountKey: ${file:/path-of-the-key.json}
```

**Comment by oscerd** [comment]
It shoud be the minimal configuration.

**Comment by simplifadmin** [comment]
Please what do you mean by minimal configuration?

**Comment by oscerd** [comment]
With these parameters configured correctly it should work.

**Comment by simplifadmin** [comment]
Please issue with the serviceAccountKey, Any idea?

```
ERROR WorkerSinkTask{id=pubsub-kafka-2} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-pubsub-kafka-2]
org.apache.kafka.connect.errors.ConnectException: Failed to create and start Camel context
at org.apache.camel.kafkaconnector.CamelSinkTask.start(CamelSinkTask.java:137)

Caused by: org.apache.camel.PropertyBindingException: Error binding property (camel.component.google-pubsub.serviceAccountKey=${file:/path-of-the/gcp_keys/pubsub-key.json}) with name: serviceAccountKey on bean: org.apache.camel.component.google.pubsub.GooglePubsubComponent@6 with value: ${file:/path-of-the/gcp_keys/pubsub-key.json
```

**Comment by simplifadmin** [comment]
Issue with Kafka-connector:

```
ERROR WorkerSinkTask{id=pubsub-kafka-1} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-pubsub-kafka-1]
2021-06-15 15:40:13,911 INFO Stopping CamelSinkTask connector task (org.apache.camel.kafkaconnector.CamelSinkTask) [task-thread-pubsub-kafka-1]
2021-06-15 15:40:13,911 INFO CamelSinkTask connector task stopped (org.apache.camel.kafkaconnector.CamelSinkTask) [task-thread-pubsub-kafka-1]
2021-06-15 15:40:13,921 ERROR WorkerSinkTask{id=pubsub-kafka-2} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-pubsub-kafka-2]

Caused by: org.apache.camel.PropertyBindingException: Error binding property (camel.component.google-pubsub.serviceAccountKey=${file:/path-of-file/gcp_keys/pubsub-key.json}) with name: serviceAccountKey on bean: org.apache.camel.component.google.pubsub.GooglePubsubComponent@189 with value: ${file:/path-of-file/gcp_keys/pubsub-key.js
```

**Comment by oscerd** [comment]
This needs to be tested first in Ckc. I don't think there is the need of brackets there. It's a camel configuration option not Kafka connect.

**Comment by simplifadmin** [comment]
I'm having no joy in getting the key to work.
Any ideas?
`camel.component.google-pubsub.serviceAccountKey: `

**Comment by qafro1** [comment]
Please any update on this ?

**Comment by oscerd** [comment]
No news at the moment. Please try it locally and place the file on your file system.

**Comment by qafro1** [comment]
I've tested this locally bin/connect-standalone.sh config/connect-standalone.properties /opt/kafka/connectors/docs/examples/CamelGooglepubsubSinkConnector.properties 
but get an error msg:

```
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: One or more messages in the publish request is empty. Each message must contain either non-empty data, or at least one attribute.
        at io.grpc.Status.asRuntimeException(Status.java:533)
        ... 13 more
[2021-06-30 17:16:10,722] INFO Stopping CamelSinkTask connector task (org.apache.camel.kafkaconnector.CamelSinkTask:210)
[2021-06-30 17:16:10,723] INFO Apache Camel 3.11.0-SNAPSHOT (camel-1) shutting down (timeout:45s) (org.apache.camel.impl.engine.AbstractCamelContext:3190)
[2021-06-30 17:16:10,729] INFO Routes shutdown summary (total:1 stopped:1) (org.apache.camel.impl.engine.AbstractCamelContext:3389)
[2021-06-30 17:16:10,729] INFO     Stopped route1 (direct://start) (org.apache.camel.impl.engine.AbstractCamelContext:3394)
[2021-06-30 17:16:10,748] INFO Apache Camel 3.11.0-SNAPSHOT (camel-1) shutdown in 24ms (uptime:3s559ms) (org.apache.camel.impl.engine.AbstractCamelContext:3330)
[2021-06-30 17:16:10,748] INFO CamelSinkTask connector task stopped (org.apache.camel.kafkaconnector.CamelSinkTask:224)
[2021-06-30 17:16:10,748] INFO [Consumer clientId=connector-consumer-CamelGoogle-pubsubSinkConnector-0, groupId=connect-CamelGoogle-pubsubSinkConnector] Revoke previously assigned partitions test-topic-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:307)
```

**Comment by oscerd** [comment]
What do you have in the kafka topic and what message are you trying to send to pubsub? It seems you have empty lines.

**Comment by qafro1** [comment]
Yes - Created Kafka topic and sent msgs like Hello world - however [GCP](https://github.com/GoogleCloudPlatform/pubsub/tree/master/kafka-connector) Kafka connector works.
Please any ideas or can you try it yourself?

**Comment by oscerd** [comment]
I'll try to have a look, but not soon. The other connector is  not based on camel..

**Comment by qafro1** [comment]
```
kind: KafkaConnector
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: pubsub
  namespace: kafka
  labels:
    # must match connect cluster name
    strimzi.io/cluster: my-connect-cluster
spec:
  tasksMax: 5
  class: org.apache.camel.kafkaconnector.googlepubsub.CamelGooglepubsubSinkConnector
  
  # use the kafka converters that better suit your needs, these are just defaults:
  #key.converter: org.apache.kafka.connect.storage.StringConverter
  #value.converter: org.apache.kafka.connect.storage.StringConverter
  config:
    # comma separated topics to get messages from
    topics: test-topic
    value.converter.schemas.enable: false
    # mandatory properties (for a complete properties list see the connector documentation):

    # The Service account key that can be used as credentials for the PubSub publisher/subscriber. It can be loaded by default from classpath, but you can prefix with classpath:, file:, or http: to load the resource from different systems.
    camel.component.google-pubsub.serviceAccountKey: ${directory:/opt/kafka/external-configuration/google:key.json}
    # The Service account key that can be used as credentials for the PubSub publisher/subscriber. It can be loaded by default from classpath, but you can prefix with classpath:, file:, or http: to load the resource from different systems.
    camel.sink.endpoint.serviceAccountKey: ${directory:/opt/kafka/external-configuration/google:key.json}
    # The Destination Name. For the consumer this will be the subscription name, while for the producer this will be the topic name.
    camel.sink.path.destinationName: test-topic
```
Issue with Kafkaconnector version 0.10.1  - Any idea?
 Caused by: org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
