### ISSUE TITLE
aws2-s3 prefix not working with Kafka source connector

### ISSUE THREAD

**Issue by arjun180** [apache/camel-kafka-connector#1235]
Hello,

I'm using a Kafka source connector to move publish json files from an s3 bucket to a Kafka topic. When my configuration looks like this - things work fine and I can use a consumer to pull down the messages. In this case, the file 'something.json' is present in the root directory of the bucket
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: s3-source-connector
  namespace : my-kafka
  labels:
    strimzi.io/cluster: my-dev-kafka-connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.aws2s3.CamelAws2s3SourceConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    topics: my-connect-topic 
    camel.source.path.bucketNameOrArn: my-kakfa-connect
    #camel.source.endpoint.useDefaultCredentials Provider: true
    camel.component.aws2-s3.useDefaultCredentialsProvider: true
    camel.component.aws2-s3.fileName: 'something.json'
    camel.source.endpoint.region: us-west-2
  ```
However, when I use camel.component.aws2-s3.prefix option and create a folder and change my yaml file to 

```
piVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: s3-source-connector
  namespace : my-kafka
  labels:
    strimzi.io/cluster: my-dev-kafka-connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.aws2s3.CamelAws2s3SourceConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    topics: my-connect-topic 
    camel.source.path.bucketNameOrArn: my-kakfa-connect
    #camel.source.endpoint.useDefaultCredentials Provider: true
    camel.component.aws2-s3.useDefaultCredentialsProvider: true
    camel.source.endpoint.region: <region>
   camel.component.aws2-s3.prefix: 'some-folder/'
```
I get the message below In the logs and nothing gets published

```
2021-07-16 22:40:09,732 INFO WorkerSourceTask{id=s3-source-connector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask) [SourceTaskOffsetCommitter-1]
```

The structure of my bucket is 

```
my-bucket
 - - some-folder
       --- something.json

```

I was wondering if I could help on this end?
