### ISSUE TITLE
Endpoint doesn't get resolved when using Camel Splunk HEC Kafka connector

### ISSUE THREAD

**Issue by arjun180** [apache/camel-kafka-connector#1241]
Hello,

I have been using the Camel Splunk HEC Kafka connector version 0.9.0 to send data from a Kafka topic to Splunk. My connector looks like this

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: splunk-sink-connector
  namespace : my-kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.splunkhec.CamelSplunkhecSinkConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    topics: <topic-name>
    camel.sink.path.splunkURL: https://hec.splunk.<my-server>.com:<port>
    camel.sink.path.token: <token>
    camel.sink.endpoint.bodyOnly: false
    camel.sink.endpoint.headersOnly: false
    camel.sink.endpoint.index: <index-name>
    camel.sink.endpoint.source: <source-name>
    camel.sink.endpoint.sourceType: 
    camel.sink.endpoint.https: true
    camel.sink.endpoint.skipTlsVerify: true
```

I get this error 

```
org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: splunk-hec://https://hec.splunk.<my-server>.com:<port>/<token>?bodyOnly=false&headersOnly=false&https=true&index=<index>&skipTlsVerify=true&source=<source-name>&sourceType=<source-type>due to: Invalid URI: splunk-hec://https://hec.splunk.<my-server>.com:<port>/<token>?bodyOnly=false&headersOnly=false&https=true&index=<index>&skipTlsVerify=true&source=<source-name>&sourceType=<source-type>
```
Why is the Splunk URL coming out to be `splunk-hec://https://hec.splunk.<my-server>.com:<port>/<token>` and not `https://hec.splunk.<my-server>.com:<port>/<token>`? Can I change it?
