### ISSUE TITLE
camel-influxdb-kafka-connector: InfluxDB Connector not usable

### ISSUE THREAD

**Issue by sonic-martin** [apache/camel-kafka-connector#1242]
# Description

Hey,

I tried to use the ```camel-influxdb-kafka-connector``` via Strimzi and Kafka Connect.
But as the Connection setup in the [Camel InfluxDB Component](https://camel.apache.org/components/latest/influxdb-component.html)  doesnt happens via String parameters, but with a Bean, it doesnt works without manually work.

# Setup

Kafka Connect and InfluxDB works and the KafkaConnector is setup like that:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: connector
  labels:
    strimzi.io/cluster: kafka-connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.influxdb.CamelInfluxdbSinkConnector
  tasksMax: 1
  config:
    topics: mytopic
    camel.sink.path.connectionBean: influxdb://influxDB
    camel.sink.endpoint.databaseName: mytopic
    camel.component.influxdb.influxDB: http://influxpath:8428
```

# Expected Result

# Actual result

Result is:
```
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: influxdb://influxdb://influxDB?databaseName=mytopic due to: No bean could be found in the registry for: influxdb://influxDB of type: org.influxdb.InfluxDB
```

# Proposed Solution

I didnt tried it, but I think the Camel InfluxDB Component has to be changed, so it also can be configured with String parameter and creating based on that the InfluxDB Class Object. Maybe that also could happen in the camel-influxdb-kafka-connector Component.
