### ISSUE TITLE
camel kafka connector - s3 source

### ISSUE THREAD

**Issue by akdevops** [apache/camel-kafka-connector#1346]
We are planning to use camel-aws2-s3-kafka-connector-0.11.5-package.tar.gz with strimzi/kafka-3.0.0 version.
With this version we want separate (new) line while consuming the data in kafka topic. 

How can we fulfill this requirement? Please help with existing (if any) solutions. 

eg.
**file added to s3 bucket - test.txt**
```
{
    "Product": "XXX",
    "ProductVertical": "XXX",
    "Payload": {
        "TrackingID": "XXX",
        "Name": "XXX",
        "UpdatedAt": "2016-04-26T19:48:40Z"       
    }
}

{
    "Product": "XXX",
    "ProductVertical": "XXX",
    "Payload": {
        "TrackingID": "XXX",
        "Name": "XXX",
        "UpdatedAt": "2016-04-26T19:48:40Z"       
    }
}
```

**Expecting output after consuming the data in kafkatopic -**  (each record should be in new separate line)
```
{"Product":"XXX","ProductVertical":"XXX","Timestamp":"2022-03-02","Payload":{"TrackingID":XXX"....}}
{"Product":"XXX","ProductVertical":"XXX","Timestamp":"2022-03-02","Payload":{"TrackingID":XXX"....}}
```
**Connector configuration -**  
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: s3-source-connector
  namespace: test
  labels:
    strimzi.io/cluster: test-connect
spec:
  class: org.apache.camel.kafkaconnector.aws2s3.CamelAws2s3SourceConnector
  tasksMax: 1
  config:
    topics: s3-test-topic
    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter

    camel.source.path.bucketNameOrArn: quickstart-kafka-s3-connector
    camel.source.endpoint.region: us-west-2
    camel.source.endpoint.useDefaultCredentialsProvider: true
    camel.component.aws2-s3.amazonS3Client: true
    camel.component.aws2-s3.includeFolders: false
```
