### ISSUE TITLE
Request to provide the KafkaConnect image for these packages

### ISSUE THREAD

**Issue by yanmxa** [apache/camel-kafka-connector#1593]
Signed-off-by: myan <myan@redhat.com>

I noticed that when creating a KafkaConnect cluster, It will include the following configuration for the KafkaConnect API
```yaml
  build:
    output:
      type: docker
      image: **/camel-kafka-connector-plugin:latest
      pushSecret: ecr-secret
    plugins:
      - name: camel-aws-s3-sink-kafka-connector
        artifacts:
          - type: tgz
            url: https://repo.maven.apache.org/maven2/org/apache/camel/kafkaconnector/camel-aws-s3-sink-kafka-connector/3.18.2/camel-aws-s3-sink-kafka-connector-3.18.2-package.tar.gz
  externalConfiguration:
```
Can we just provide the image for the different packages? Creating a new image registry and configuring the pull secret isn't necessary to run it.
