### ISSUE TITLE
RabbitMQ connector enabling TLS connection

### ISSUE THREAD

**Issue by jakubmalek** [apache/camel-kafka-connector#1718]
I'm struggle to find an option to enable TLS connection for RabbitMQ client in the connector.

Looking at the [spring-rabbitmq-source.kamelet.yaml](https://github.com/apache/camel-kamelets/blob/v4.11.0/kamelets/spring-rabbitmq-source.kamelet.yaml) file I see that the Camel component is configured with `connectionFactory` bean from the Spring.
- At first glance, the `CachingConnectionFactory` interface doesn't have any method for enabling TLS
- One option is to set `com.rabbitmq.client.ConnectionFactory` instance configured with TLS in the `CachingConnectionFactory` constructor.
- The other, which is more easy for Kamelet, is to set the URI parameter instead of a host name where its possible to define the protocol e.g. `amqp://localhost` or `amqps://localhost` for TLS connections.

So unless there is an easier way (that I missed) to enable TLS, my proposal is to change the Kamelet to

```yaml
...
properties:
  ...
  protocol:
    title:  Protocol
    description: The AMQP protocol to use.
    type: string
    enum: ["amqp", "amqps"]
    default: "amqp"
  dependencies:
    - "camel:spring-rabbitmq"
    - "camel:kamelet"
  template:
    beans:
      - name: connectionFactory
        type: "#class:org.springframework.amqp.rabbit.connection.CachingConnectionFactory"
        properties:
          username: '{{?username}}'
          password: '{{?password}}'
          uri: '{{protocol}}://{{host}}:{{port}}'
          virtualHost: "{{vhost}}"
...
```

With `protocol` configured, we can enable or disable TLS.
