### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.camel.kafkaconnector.CamelSinkConnectorConfig

### ISSUE THREAD

**Issue by saranyaeu2987** [apache/camel-kafka-connector#251]
I am trying to run camel-kafka-connector in my minikube and Strimzi but getting 
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.camel.kafkaconnector.CamelSinkConnectorConfig

Here is my image Docker file

```
FROM strimzi/kafka:0.18.0-kafka-2.5.0
USER root:root
COPY ./my-plugins/ /opt/kafka/plugins/
USER 1001
```

Here is my plugins folder contains the following jars 
<img width="1602" alt="Screen Shot 2020-05-27 at 10 25 32 PM" src="https://user-images.githubusercontent.com/19850718/83171319-8c478200-a0db-11ea-974e-7bc6c313b649.png">

When I see the pod logs, this is what I see
```
2020-05-28 16:17:11,313 INFO Registered loader: PluginClassLoader{pluginLocation=file:/opt/kafka/plugins/camel-kafka-connector-0.2.0.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader) [main]
2020-05-28 16:17:11,313 INFO Added plugin 'org.apache.camel.kafkaconnector.CamelSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader) [main]
2020-05-28 16:17:11,313 INFO Added plugin 'org.apache.camel.kafkaconnector.CamelSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader) [main]
2020-05-28 16:17:11,313 INFO Added plugin 'org.apache.camel.kafkaconnector.transforms.CamelTypeConverterTransform$Key' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader) [main]
2020-05-28 16:17:11,313 INFO Added plugin 'org.apache.camel.kafkaconnector.transforms.CamelTypeConverterTransform$Value' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader) [main]
```

I dont see org.apache.camel.kafkaconnector.CamelSinkConnectorConfig getting loaded from camel-kafka-connector-0.2.0.jar
 Which I feel would have caused the following error 

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.camel.kafkaconnector.CamelSinkConnectorConfig
	at org.apache.camel.kafkaconnector.CamelSinkConnector.config(CamelSinkConnector.java:67)
	at org.apache.kafka.connect.connector.Connector.validate(Connector.java:129)
...
```
**Full log from connector pod **
[logs-from-my-connect-cluster-connect-in-my-connect-cluster-connect-8866c5d89-rd4zs.txt](https://github.com/apache/camel-kafka-connector/files/4697195/logs-from-my-connect-cluster-connect-in-my-connect-cluster-connect-8866c5d89-rd4zs.txt)

Any suggestions??

**Comment by oscerd** [comment]
Can you please show your configuration file?

**Comment by saranyaeu2987** [comment]
Here is my kafkaconnect Strimzi deployment yaml file

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: selumalai/selumalai-s3-kafkaconnect #(Docker file definition in above comment where my-plugins contains all camel connector jars)
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
  replicas: 1
  bootstrapServers: 34.212.160.12:9092
  externalConfiguration:
    volumes:
      - name: aws-credentials
        secret:
          secretName: aws-credentials
  config:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false

```

Here is my KafkaConnector deployment file

```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: s3-sink-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.CamelSinkConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    topics: my-replicated-topic
    camel.sink.url: aws-s3://selumalai-kafka-s3?keyName=${date:now:yyyyMMdd-HHmmssSSS}-${exchangeId}
    camel.sink.maxPollDuration: 10000
    camel.component.aws-s3.configuration.autocloseBody: false
    camel.component.aws-s3.accessKey: ${file:/opt/kafka/external-configuration/aws-credentials/aws-credentials.properties:aws_access_key_id}
    camel.component.aws-s3.secretKey: ${file:/opt/kafka/external-configuration/aws-credentials/aws-credentials.properties:aws_secret_access_key}
    camel.component.aws-s3.region: US_WEST_2

```

**Comment by valdar** [comment]
@saranyaeu2987 can you please try with this dockerfile:
```FROM strimzi/kafka:0.18.0-kafka-2.5.0
USER root:root
COPY ./my-plugins/ /opt/kafka/plugins/camel-aws-s3/
USER 1001```

**Comment by saranyaeu2987** [comment]
Worked. Thanks a lot!!

**Comment by oscerd** [comment]
The simple language is not resolved in the sink.url

**Comment by saranyaeu2987** [comment]
@valdar @oscerd 

I want my CamelSinkConnector(s3) to consume in batches of 1000 messages or for interval of 10seconds.
How can I set this property in yaml file ?

**Comment by oscerd** [comment]
The S3 sink connector doens't provide a batch size option because it's mapped on the camel producer options actually. The producer doesn't work as a batch job.

**Comment by saranyaeu2987** [comment]
So, this property **CamelBatchSize** in https://camel.apache.org/manual/latest/batch-consumer.html
will not be applicable to s3sink connector?

**Comment by oscerd** [comment]
Yes, because you're mixing up the concepts: a consumer in Camel wii be used when you're using a Source connector, so you'll have the consumer options in that case.
For example if you use the source connector you can set the 

camel.source.endpoint.maxMessagesPerPoll 

And define how much messages will be part of the batch consumed.

On the sink side you will be using the producer option. 

Source options: https://camel.apache.org/camel-kafka-connector/latest/connectors/camel-aws-s3-kafka-source-connector.html
Sink options: https://camel.apache.org/camel-kafka-connector/latest/connectors/camel-aws-s3-kafka-sink-connector.html

You're using a sink connector (in Camel terms you're using a producer)

**Comment by saranyaeu2987** [comment]
Got it. 
I wanted to add variable date in camel.sink.url. is there a way to add it. 
without variable part, the file in S3 is getting overwritten. 

Here is my yaml file for your reference 
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: s3-sink-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.CamelSinkConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    topics: my-replicated-topic
    camel.sink.url: aws-s3://selumalai-kafka-s3?keyName=${date:now:yyyyMMdd-HHmmssSSS}-${exchangeId}
    camel.sink.maxPollDuration: 10000
    camel.component.aws-s3.configuration.autocloseBody: false
    camel.component.aws-s3.accessKey: ${file:/opt/kafka/external-configuration/aws-credentials/aws-credentials.properties:aws_access_key_id}
    camel.component.aws-s3.secretKey: ${file:/opt/kafka/external-configuration/aws-credentials/aws-credentials.properties:aws_secret_access_key}
    camel.component.aws-s3.region: US_WEST_2
```
