### ISSUE TITLE
Question: How to provide aws role:arn value to authenticate S3 

### ISSUE THREAD

**Issue by saranyaeu2987** [apache/camel-kafka-connector#267]
Hi, 
I am using strimzi kafka connect to push data into S3 using camel-s3-sink-connector.
I wanted to use IAM role authentication instead of access key and secret.

How should I need to provide AWS role:arn in my yaml file when **camel.component.aws-s3.useIAMCredentials: true**??

Sample deployment file (reference: https://developers.redhat.com/blog/2020/02/14/using-secrets-in-apache-kafka-connect-configuration/)
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: s3-sink-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.CamelSinkConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    topics: abc_abc
    camel.sink.url: aws-s3://testse1232?keyName=s3-connect/${date:now:yyyyMMdd-HHmmssSSS}
    camel.component.aws-s3.configuration.autocloseBody: false
    camel.component.aws-s3.useIAMCredentials: true
```
